name: Weekly Update

on: 
  schedule:
    - cron: '0 2 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
		
    - name: Work
      env:
        MY_CONFIG_JSON: ${{ secrets.MY_CONFIG_JSON }}
      run: 
        python auto.py
		
    - name: commit
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m 'update new opml' || echo "nothing to commit"
		
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}