name: Weekly Update

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Work
      env:
        MY_CONFIG_JSON: ${{ secrets.MY_CONFIG_JSON }}
      run: 
        python auto.py prod
    - name: commit to this repo
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m 'update new opml' || echo "nothing to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # 接下来提交到EuDs63/EuDs63.github.io仓库
    - name: clone EuDs63/EuDs63.github.io
      uses: actions/checkout@v3
      with:
        repository: 'EuDs63/EuDs63.github.io'
    - name: copy file to another repo
      run: |
        ls ../

    # 把修改后的数据提交到 GitHub 仓库
    - name: Git Add and Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'update rss data'
        add: './data/rss'