name: Weekly Update

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Work
      env:
        MY_CONFIG_JSON: ${{ secrets.MY_CONFIG_JSON }}
      run: 
        python auto.py prod
    - name: commit to this repo
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m 'update new opml' || echo "nothing to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}





    

